const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEMS: "ADD_ITEMS",
  REMOVE_ITEMS: "REMOVE_ITEMS",
  CLEAR_ITEMS_FROM_CART: "CLEAR_ITEMS_FROM_CART",
};
export default CartActionTypes;
